### ISSUE TITLE
 replace the  uv random noise

### ISSUE THREAD

**Issue by zhoushiwei** [postech-ami/paint-it#10]
Hi, if I take this input uv and replace the random noise with a texture that is locally close to the 3D template model, what other parameters do I need to change to make the result more robust?

**Comment by Youwang-Kim** [comment]
Hi, thanks for your interest in our work.

As far as I understand, you want to query the template UV texture rather than the random noise that we used as the U-Net input. Is this correct?

Since our DC-PBR (U-Net part) borrows the principle of Deep Image Prior, I think using random noise rather than some structured input would help achieve better results.

Please let us know if you have more questions.

Thanks

**Comment by zhoushiwei** [comment]
Yes, I am now trying to replace the random noise with the texture map corresponding to the input mesh, for example, I now want to recover the dog texture, so I input the pre-prepared dog mesh and texture, and I found that the actual effect is that some of them will be better, and some of them will not be better. Another problem is that I found that the oversaturation is a bit serious now, many samples are better at 700 iterations than at 1500 iterations. By the way, I feel that the texture effect is hard to be utilized in practice, and it seems that there is a big gap between the effect I recovered and the result shown in your paper, I don't know what causes it!

**Comment by Youwang-Kim** [comment]
Regarding oversaturation, you may need to find the number of iterations that produce the best quality texture maps, depending on your target meshes. Also, note that the resolution of the meshes (i.e., the number of vertices) or the quality of UV texture mapping matters when synthesizing PBR texture maps.

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
