### ISSUE TITLE
how to change the size ,if the UV size is 1024 or 2048

### ISSUE THREAD

**Issue by ghost** [postech-ami/paint-it#11]
The DC-PBR representation uses U-Net as its architecture. Thus, if you increase the resulting texture map resolution, you would have to modify some architectural hyperparameters such as `num_channels_down`, `num_channels_up`, `num_channels_skip`, `filter_size_up`, `filter_size_down`. You can adjust those parameters here.
https://github.com/postech-ami/Paint-it/blob/407c55b4255dd8e13fd950313ea860cf0ffe71e2/paint_it.py#L81-L87

Please let us know if you have more questions.
Thanks.

_Originally posted by @Youwang-Kim in https://github.com/postech-ami/Paint-it/issues/8#issuecomment-2048921114_

**Comment by Youwang-Kim** [comment]
Hi, thanks for your interest in our work. 

We haven't tried increasing the UV size. So maybe you could try adjusting the architectural hyperparameters such as `num_channels_down`, `num_channels_up`, `num_channels_skip`, `filter_size_up`, `filter_size_down`, so that you could increase the number of parameters and the learning capacity of the DC-PBR part.

Please let us know if you have more questions.

Thanks.

**Comment by AIGCAI** [comment]
> Hi, thanks for your interest in our work.
> 
> We haven't tried increasing the UV size. So maybe you could try adjusting the architectural hyperparameters such as `num_channels_down`, `num_channels_up`, `num_channels_skip`, `filter_size_up`, `filter_size_down`, so that you could increase the number of parameters and the learning capacity of the DC-PBR part.
> 
> Please let us know if you have more questions.
> 
> Thanks.

ok ,I have run it  ,the net don't need modify , I just modify the SD network to support 1024

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
